# Generated by Django 3.1.2 on 2022-06-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burgerApi', '0002_mycustomerdetail_myingredient_myorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='account_type',
            field=models.CharField(choices=[('owner', 'Car Owner'), ('client', 'Client')], default='client', help_text='Car Owner can use their car(s) for renting/Clients can rent car once a day.', max_length=64),
        ),
    ]
