# Generated by Django 3.1.2 on 2022-06-29 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('burgerApi', '0003_myuser_account_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=264)),
                ('car_detail', models.TextField(max_length=1024, verbose_name='car Description')),
                ('car_rent_price', models.FloatField()),
                ('car_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'CarCategories',
            },
        ),
        migrations.CreateModel(
            name='CarRent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentDate', models.DateTimeField(auto_now_add=True)),
                ('car', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='burgerApi.car')),
            ],
        ),
        migrations.RemoveField(
            model_name='myorder',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='myorder',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='myorder',
            name='user',
        ),
        migrations.RenameField(
            model_name='mycustomerdetail',
            old_name='delivery_address',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='account_type',
            field=models.CharField(default='client', help_text='Car Owner can use their car(s) for renting/Clients can rent car once a day.', max_length=64),
        ),
        migrations.DeleteModel(
            name='MyIngredient',
        ),
        migrations.DeleteModel(
            name='MyOrder',
        ),
        migrations.AddField(
            model_name='carrent',
            name='customer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='burgerApi.mycustomerdetail'),
        ),
        migrations.AddField(
            model_name='carrent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='car',
            name='car_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_category', to='burgerApi.carcategory'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
